spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: payments
          predicates:
            - Path=/api/payments/**
          uri: lb://PAYMENTS-SERVICE
          filters:
            - RewritePath=/api(?<segment>.*), $\{segment}
        - id: shop
          predicates:
            - Path=/api/shop/**
          uri: lb://SHOP-SERVICE
          filters:
            - RewritePath=/api/shop(?<segment>.*), $\{segment}
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8000/auth/realms/cloud
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: cloud-service
postLogoutRedirectUrl: http://localhost:8080
logging:
  level:
    org:
      springframework:
        cloud.gateway: DEBUG
        http.server.reactive: DEBUG
        web.reactive: DEBUG