spring:
  cloud:
    gateway:
      - id: payments
        predicates:
          - Path=/api/payments
        uri: lb://PAYMENTS-SERVICE
        filters:
          - RewritePath=/api/(?<payments>.*), /$\{payments}
